### ISSUE TITLE
Do not crash the application on Wealth Tracker JsonException

### ISSUE THREAD

**Issue by leMicin** [Sidekick-Poe/Sidekick#150]
```

2023-12-08 20:50:07.271 -05:00 [INF] No migrations were applied. The database is already up to date.
2023-12-08 20:50:07.271 -05:00 [INF] Start processing HTTP request GET https://api.pathofexile.com/stash/Affliction/566dd2a833
2023-12-08 20:50:07.271 -05:00 [INF] Sending HTTP request GET https://api.pathofexile.com/stash/Affliction/566dd2a833
2023-12-08 20:50:07.500 -05:00 [INF] Received HTTP response headers after 228.6834ms - 503
2023-12-08 20:50:07.500 -05:00 [INF] End processing HTTP request after 228.8162ms - 503
2023-12-08 20:50:07.503 -05:00 [ERR] [Poe Api Client] Could not fetch ApiStashTabWrapper at https://api.pathofexile.com/stash/Affliction/566dd2a833.
2023-12-08 20:50:07.505 -05:00 [FTL] Unhandled exception.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Sidekick.Apis.Poe.Clients.PoeApiClient.Fetch[TReturn](String path)
   at Sidekick.Apis.Poe.Stash.StashService.GetStashDetails(String id)
   at Sidekick.Modules.Wealth.WealthParser.ParseLoop()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-12-08 20:50:07.726 -05:00 [DBG] Adding entry for "40be4e3b-c3b0-4547-9762-678b18a4a864"/MudBlazor.MudPopoverProvider. 1 total observers after add.
2023-12-08 20:50:07.726 -05:00 [DBG] Updating entry for "40be4e3b-c3b0-4547-9762-678b18a4a864"/MudBlazor.MudPopoverProvider. 1 total observers.

```

**Comment by leMicin** [comment]
```
2023-12-17 12:29:05.342 -05:00 [ERR] [Poe Api Client] Could not fetch ApiStashTabWrapper at https://api.pathofexile.com/stash/Affliction/16d3926d13/42177b7e2a.
2023-12-17 12:29:05.344 -05:00 [FTL] Unhandled exception.
System.Text.Json.JsonException: 'e' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Sidekick.Apis.Poe.Clients.PoeApiClient.Fetch[TReturn](String path)
   at Sidekick.Apis.Poe.Stash.StashService.FetchStashItems(ApiStashTab tab)
   at Sidekick.Apis.Poe.Stash.StashService.FetchStashItems(ApiStashTab tab)
   at Sidekick.Apis.Poe.Stash.StashService.GetStashDetails(String id)
   at Sidekick.Modules.Wealth.WealthParser.ParseLoop()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
2023-12-17 12:29:05.513 -05:00 [DBG] Adding entry for "15dee0bb-78c5-46e1-81e2-9986075a452b"/MudBlazor.MudPopoverProvider. 1 total observers after add.
2023-12-17 12:29:05.513 -05:00 [DBG] Updating entry for "15dee0bb-78c5-46e1-81e2-9986075a452b"/MudBlazor.MudPopoverProvider. 1 total observers.
2023-12-17 13:41:59.102 -05:00 [DBG] Adding entry for "fac2a7ef-4b29-4f4b-89b6-79e7e756fec9"/MudBlazor.MudPopoverProvider. 1 total observers after add.
2023-12-17 13:41:59.112 -05:00 [DBG] Updating entry for "fac2a7ef-4b29-4f4b-89b6-79e7e756fec9"/MudBlazor.MudPopoverProvider. 1 total observers.
2023-12-17 13:41:59.247 -05:00 [INF] Start processing HTTP request GET https://www.pathofexile.com/api/trade/data/leagues
2023-12-17 13:41:59.249 -05:00 [INF] Sending HTTP request GET https://www.pathofexile.com/api/trade/data/leagues
2023-12-17 13:41:59.412 -05:00 [INF] Received HTTP response headers after 162.1214ms - 403
2023-12-17 13:41:59.412 -05:00 [INF] End processing HTTP request after 168.3136ms - 403
2023-12-17 13:41:59.416 -05:00 [INF] [Trade Client] Could not fetch ApiLeague at https://www.pathofexile.com/api/trade/data/leagues.
2023-12-17 13:41:59.461 -05:00 [ERR] System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Sidekick.Apis.Poe.Clients.PoeTradeClient.Fetch[TReturn](String path, Boolean useDefaultLanguage)
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList()
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
   at Sidekick.Modules.Settings.Setup.Setup.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at Sidekick.Apis.Poe.Clients.PoeTradeClient.Fetch[TReturn](String path, Boolean useDefaultLanguage)
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList()
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
   at Sidekick.Modules.Settings.Setup.Setup.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
