### ISSUE TITLE
Sidekick errors out at first start - Error about official trade API

### ISSUE THREAD

**Issue by nexulh** [Sidekick-Poe/Sidekick#315]
A red error window is shown saying that the official trade site might be down. It isn't. 

According to the log file Sidekick has a problem parsing the response from https://www.pathofexile.com/api/trade2/data/leagues

I manually tried the URL and got the following response:
{"result":[{"id":"Standard","realm":"poe2","text":"Standard"},{"id":"Hardcore","realm":"poe2","text":"Hardcore"}]}

Might something have changed with the JSON response from this endpoint recently?

As I check Taskmanager, only "Sidekick Setup" is shown, not "Sidekick", so I'm assuming it's getting stuck in the setup stage somewhere. 

Excerpt from the logfile:
`2024-12-17 20:57:29.692 +01:00 [INF] Start processing HTTP request GET https://www.pathofexile.com/api/trade2/data/leagues
2024-12-17 20:57:29.695 +01:00 [INF] Sending HTTP request GET https://www.pathofexile.com/api/trade2/data/leagues
2024-12-17 20:57:29.726 +01:00 [INF] Start processing HTTP request GET https://www.pathofexile.com/api/trade/data/leagues
2024-12-17 20:57:29.726 +01:00 [INF] Sending HTTP request GET https://www.pathofexile.com/api/trade/data/leagues
2024-12-17 20:57:29.832 +01:00 [INF] Received HTTP response headers after 103.1663ms - 403
2024-12-17 20:57:29.832 +01:00 [INF] Received HTTP response headers after 133.9553ms - 403
2024-12-17 20:57:29.834 +01:00 [INF] End processing HTTP request after 107.8318ms - 403
2024-12-17 20:57:29.834 +01:00 [INF] End processing HTTP request after 147.2653ms - 403
2024-12-17 20:57:29.851 +01:00 [INF] [Trade Client] Could not fetch ApiLeague at https://www.pathofexile.com/api/trade2/data/leagues.
2024-12-17 20:57:29.851 +01:00 [INF] [Trade Client] Could not fetch ApiLeague at https://www.pathofexile.com/api/trade/data/leagues.
2024-12-17 20:57:29.853 +01:00 [ERR] [LeagueProvider] Error fetching leagues.
System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
   at Sidekick.Apis.Poe.Clients.PoeTradeClient.Fetch[TReturn](GameType game, IGameLanguage language, String path)
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.Fetch(GameType game)
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.FetchAll()
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
2024-12-17 20:57:29.874 +01:00 [ERR] An error occured while executing a component.
Sidekick.Common.Exceptions.ApiErrorException: An error occured while trying to get the results from the official trade API. The official trade website may be down. Please try again later or open a ticket on github.
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
   at Sidekick.Common.Blazor.Setup.Setup.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-12-17 20:57:29.876 +01:00 [ERR] Sidekick.Common.Exceptions.ApiErrorException: An error occured while trying to get the results from the official trade API. The official trade website may be down. Please try again later or open a ticket on github.
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
   at Sidekick.Common.Blazor.Setup.Setup.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Sidekick.Common.Exceptions.ApiErrorException: An error occured while trying to get the results from the official trade API. The official trade website may be down. Please try again later or open a ticket on github.
   at Sidekick.Apis.Poe.Leagues.LeagueProvider.GetList(Boolean fromCache)
   at Sidekick.Common.Blazor.Setup.Setup.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
2024-12-17 20:57:38.418 +01:00 [INF] [GitHubClient] GitHub download indicator file already exists.`

**Comment by Maxxgold** [comment]
+1

**Comment by aplomBomb** [comment]
it appears the trade site is indeed down

**Comment by leMicin** [comment]
Fixed for now, but we need to improve as well https://github.com/Sidekick-Poe/Sidekick/issues/316

**Comment by sevenfourSF** [comment]
Hi, it was the first launch, and I immediately got an error. I found this branch through Discord where you said you fixed it. What exactly did you fix, or how can I fix it myself?

![Снимок экрана 2024-12-18 041908](https://github.com/user-attachments/assets/e1d04407-1348-4325-9480-e4c70aa38d6f)

**Comment by leMicin** [comment]
Yeah it got back pretty soon after, we are working on mitigation steps when it next happens.
